### ISSUE TITLE
I2C Mem_Write sends a repeated start

### ISSUE THREAD

**Issue by JeremyGrosser** [JeremyGrosser/rp2040_hal#33]
See conversation on Gitter for details.

**Comment by hgrodriguez** [comment]
as requested by Jeremy I am attaching the pictures of the logic analyser
![MicroPython_Write_Correct](https://user-images.githubusercontent.com/52081159/155847937-c47c75fc-ed19-435d-982c-940dead811a5.PNG)
![RP2040_Write_Correct](https://user-images.githubusercontent.com/52081159/155847938-44a90dcb-30f9-4a06-8fb2-86df656dcae9.PNG)
![RP2040_Write_Wrong](https://user-images.githubusercontent.com/52081159/155847939-cd17e203-e3dd-4c34-b8eb-2b2037e099de.PNG)

**Comment by hgrodriguez** [comment]
I am afraid, that maybe Mem_Read needs fixing, too.

**Comment by JeremyGrosser** [comment]
I changed Mem_Write to use a single Master_Transmit rather than a repeated start between address and data (5879969b90cb0890e3ab445f598431037e00973c).

Mem_Read needs the repeated start because it has to change the I2C address' LSB from write to read between sending the memory address and reading the data.

![EEPROM write trace](https://pub.synack.me/page_write.jpg)
![EEPROM read trace](https://pub.synack.me/page_read.jpg)
