### ISSUE TITLE
I2C Mem_Write might raise Constraint_Error

### ISSUE THREAD

**Issue by RREE** [JeremyGrosser/rp2040_hal#42]
Line 305 in rp-master.adb reads:
`A : constant I2C_Data (1 .. 1) := (1 => UInt8 (Mem_Addr));`
This raises CE if Mem_Addr > 255. 
It should be written as
`A : constant I2C_Data (1 .. 1) := (1 => UInt8 (16#FF# and Mem_Addr));`

**Comment by RREE** [comment]
Same case in line 345 for Mem_Read

**Comment by JeremyGrosser** [comment]
This is intentional. You cannot not use a `Mem_Addr > 255` when `Mem_Addr_Size = Memory_Size_8b`. If you need to use a 16-bit memory address, then you should set `Mem_Addr_Size` to `Memory_Size_16b`.

**Comment by RREE** [comment]
OK, makes sense. Can be closed.
