### ISSUE TITLE
Latest release on alire

### ISSUE THREAD

**Issue by ThyMYthOS** [JeremyGrosser/rp2040_hal#56]
@JeremyGrosser when will v2.1.1 be available on alire?

**Comment by JeremyGrosser** [comment]
I submitted it [a while ago](https://github.com/alire-project/alire-index/pull/858), but the CI run failed and the PR went stale. I think switching to the newer toolchain might fix it. This is already done on the rp2040_hal master branch, but I haven't tried resubmitting it to alire-index yet.

I can work on that next week.

**Comment by JeremyGrosser** [comment]
See https://github.com/alire-project/alire-index/pull/978

**Comment by JeremyGrosser** [comment]
rp2040_hal 2.2.1 is now in the alire community index. Run `alr index --update-all` before updating the version in your project's alire.toml.
