### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by ThyMYthOS** [JeremyGrosser/rp2040_hal#59]
`usb_embedded` now requires hal 0.4

https://github.com/JeremyGrosser/rp2040_hal/blob/3ff0c10732738547dda32bdb21d3bffbcf6b9265/alire.toml#L15

**Comment by JeremyGrosser** [comment]
If I change hal to 0.4 in rp2040_hal, it conflicts with the cortex_m crate, which still depends on 0.3

**Comment by JeremyGrosser** [comment]
rp2040_hal 2.4.0 has been tagged and depends on the latest 1.0.0 deps.

Alire index submission: https://github.com/alire-project/alire-index/pull/1271
