### ISSUE TITLE
GigBarMove plus ILS ChauvetDJ Item code 10051948

### ISSUE THREAD

**Issue by dinashdaniel** [JeremyGrosser/rp2040_hal#60]
Asking me to connect USB stick on the menu screen. I can't activate anything. I hardly used the unit, which was about 1 year old. I am in Melbourne, Australia, and I bought it from DJ City. Where can I get this USB stick as none came with the unit?

**Comment by JeremyGrosser** [comment]
I have no idea what a GigBarMove is. You're very much in the wrong place.
