### ISSUE TITLE
PLL_SYS configuration

### ISSUE THREAD

**Issue by Fabien-Chouteau** [JeremyGrosser/rp2040_hal#63]
Hi @JeremyGrosser,

I was about to submit a PR that allows custom PLL_SYS configuration from the `RP.Clock.Initialize` procedure:
```diff
-   procedure Initialize
-      (XOSC_Frequency     : XOSC_Hertz := 0;
-       XOSC_Startup_Delay : XOSC_Cycles := 770_048) --  ~64ms with a 12 MHz crystal
+   procedure Initialize
+      (XOSC_Frequency     : XOSC_Hertz := 0;
+       XOSC_Startup_Delay : XOSC_Cycles := 770_048; --  ~64ms with a 12 MHz crystal
+       SYS_PLL_Config     : PLL_Config := PLL_125_MHz)
```
But I wonder if this is the best way. I'd like to have your opinion first.

Is it possible to change the config of PLL_SYS after calling `RP.Clock.Initialize`? What will be the effect on peripherals that are already configured?

Cheers,

**Comment by JeremyGrosser** [comment]
My intent was that you could call `Configure_PLL` to change the clock speed after `Initialize`, though looking at the code now I see that `FC0_REF_KHZ` doesn't get updated in that case. I think that's a bug.

Any peripherals configured before a clock frequency change will need to have their `Configure` procedure called again.

This is how I imagined it working:
```ada
RP.Clock.Initialize (12_000_000);
RP.Clock.Set_SYS_Source (RP.Clock.XOSC); --  or some other already running clock
RP.Clock.Configure_PLL (RP.Clock.PLL_250MHz);
RP.Clock.Set_SYS_Source (RP.Clock.PLL_SYS);
```

If you'd prefer to add it as a parameter to `RP.Clock.Initialize` then that's fine with me.
